name: Deploy To Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git config --global --add safe.directory /var/www/elevatia
            cd /var/www/elevatia
            git fetch origin
            sudo git reset --hard origin/main

            # Ensure correct permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            sudo composer install --no-interaction --prefer-dist --optimize-autoloader

            sudo php artisan config:clear
            sudo php artisan route:clear
            sudo php artisan view:clear
            sudo php artisan cache:clear

            sudo php artisan migrate --force

            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan optimize:clear
