name: Deploy To Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git config --global --add safe.directory /var/www/elevatia
            cd /var/www/elevatia
            git pull origin main
            sudo chmod -R 775 storage bootstrap/cache storage/framework/cache storage/logs storage/framework/views
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan cache:clear
            php artisan migrate --force
            php artisan permissions:sync
            php artisan db:seed
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize:clear
